//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.DesktopApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.DesktopApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need administrator access to set system DNS.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exists.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accessing the Registry for the requested information.
        /// </summary>
        internal static string AnErrorOccurredWhileAccessingTheRegistryForTheRequestedInformation {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileAccessingTheRegistryForTheRequestedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing an Instance that was returned.
        /// </summary>
        internal static string AnErrorOccurredWhileProcessingAnInstanceThatWasReturned {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileProcessingAnInstanceThatWasReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon app_connected {
            get {
                object obj = ResourceManager.GetObject("app_connected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon app_disconnected {
            get {
                object obj = ResourceManager.GetObject("app_disconnected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon broken_link {
            get {
                object obj = ResourceManager.GetObject("broken_link", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon connected {
            get {
                object obj = ResourceManager.GetObject("connected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHCP not enabled on adapter.
        /// </summary>
        internal static string DHCPNotEnabledOnAdapter {
            get {
                return ResourceManager.GetString("DHCPNotEnabledOnAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon disconnected {
            get {
                object obj = ResourceManager.GetObject("disconnected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate network number.
        /// </summary>
        internal static string DuplicateNetworkNumber {
            get {
                return ResourceManager.GetString("DuplicateNetworkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File copy failed.
        /// </summary>
        internal static string FileCopyFailed {
            get {
                return ResourceManager.GetString("FileCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame/network number bounds error.
        /// </summary>
        internal static string FrameNetworkNumberBoundsError {
            get {
                return ResourceManager.GetString("FrameNetworkNumberBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface not configurable.
        /// </summary>
        internal static string InterfaceNotConfigurable {
            get {
                return ResourceManager.GetString("InterfaceNotConfigurable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name.
        /// </summary>
        internal static string InvalidDomainName {
            get {
                return ResourceManager.GetString("InvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid frame type.
        /// </summary>
        internal static string InvalidFrameType {
            get {
                return ResourceManager.GetString("InvalidFrameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid gateway IP address.
        /// </summary>
        internal static string InvalidGatewayIPAddress {
            get {
                return ResourceManager.GetString("InvalidGatewayIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host name.
        /// </summary>
        internal static string InvalidHostName {
            get {
                return ResourceManager.GetString("InvalidHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input parameter.
        /// </summary>
        internal static string InvalidInputParameter {
            get {
                return ResourceManager.GetString("InvalidInputParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address.
        /// </summary>
        internal static string InvalidIPAddress {
            get {
                return ResourceManager.GetString("InvalidIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid network number.
        /// </summary>
        internal static string InvalidNetworkNumber {
            get {
                return ResourceManager.GetString("InvalidNetworkNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security parameter.
        /// </summary>
        internal static string InvalidSecurityParameter {
            get {
                return ResourceManager.GetString("InvalidSecurityParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid subnet mask.
        /// </summary>
        internal static string InvalidSubnetMask {
            get {
                return ResourceManager.GetString("InvalidSubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid system path.
        /// </summary>
        internal static string InvalidSystemPath {
            get {
                return ResourceManager.GetString("InvalidSystemPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP not enabled on adapter.
        /// </summary>
        internal static string IPNotEnabledOnAdapter {
            get {
                return ResourceManager.GetString("IPNotEnabledOnAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPX not enabled on adapter.
        /// </summary>
        internal static string IPXNotEnabledOnAdapter {
            get {
                return ResourceManager.GetString("IPXNotEnabledOnAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not supported on this platform.
        /// </summary>
        internal static string MethodNotSupportedOnThisPlatform {
            get {
                return ResourceManager.GetString("MethodNotSupportedOnThisPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 5 gateways specified.
        /// </summary>
        internal static string MoreThan5GatewaysSpecified {
            get {
                return ResourceManager.GetString("MoreThan5GatewaysSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network adapter not found.
        /// </summary>
        internal static string NetworkAdapterNotFound {
            get {
                return ResourceManager.GetString("NetworkAdapterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not connected to the internet..
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter or select your DNS&apos;s IP.
        /// </summary>
        internal static string NoDNS {
            get {
                return ResourceManager.GetString("NoDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No primary/secondary WINS server defined.
        /// </summary>
        internal static string NoPrimarySecondaryWINSServerDefined {
            get {
                return ResourceManager.GetString("NoPrimarySecondaryWINSServerDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all DHCP leases could be released/renewed.
        /// </summary>
        internal static string NotSllDHCPLeasesCouldBeReleasedRenewed {
            get {
                return ResourceManager.GetString("NotSllDHCPLeasesCouldBeReleasedRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory.
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter out of bounds.
        /// </summary>
        internal static string ParameterOutOfBounds {
            get {
                return ResourceManager.GetString("ParameterOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path, file or object not found.
        /// </summary>
        internal static string PathfileOrObjectNotFound {
            get {
                return ResourceManager.GetString("PathfileOrObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know about this issue..
        /// </summary>
        internal static string ReportIssue {
            get {
                return ResourceManager.GetString("ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful completion, no reboot required.
        /// </summary>
        internal static string SuccessfulCompletionNoRebootRequired {
            get {
                return ResourceManager.GetString("SuccessfulCompletionNoRebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful completion, reboot required.
        /// </summary>
        internal static string SuccessfulCompletionRebootRequired {
            get {
                return ResourceManager.GetString("SuccessfulCompletionRebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to configure DHCP service.
        /// </summary>
        internal static string UnableToConfigureDHCPService {
            get {
                return ResourceManager.GetString("UnableToConfigureDHCPService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to configure TCP/IP service.
        /// </summary>
        internal static string UnableToConfigureTCPIPService {
            get {
                return ResourceManager.GetString("UnableToConfigureTCPIPService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to notify DNS service.
        /// </summary>
        internal static string UnableToNotifyDNSService {
            get {
                return ResourceManager.GetString("UnableToNotifyDNSService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to notify service.
        /// </summary>
        internal static string UnableToNotifyService {
            get {
                return ResourceManager.GetString("UnableToNotifyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to release DHCP lease.
        /// </summary>
        internal static string UnableToReleaseDHCPLease {
            get {
                return ResourceManager.GetString("UnableToReleaseDHCPLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to renew DHCP lease.
        /// </summary>
        internal static string UnableToRenewDHCPLease {
            get {
                return ResourceManager.GetString("UnableToRenewDHCPLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems some unknown errors happend!.
        /// </summary>
        internal static string UnknownErrorHappend {
            get {
                return ResourceManager.GetString("UnknownErrorHappend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown failure.
        /// </summary>
        internal static string UnknownFailure {
            get {
                return ResourceManager.GetString("UnknownFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected network doesn&apos;t have connection to the internet and you&apos;re going to disconnect..
        /// </summary>
        internal static string YoureGoingToDC {
            get {
                return ResourceManager.GetString("YoureGoingToDC", resourceCulture);
            }
        }
    }
}
